### ISSUE TITLE
".../install/" does not work anymore

### ISSUE THREAD

**Issue by mbrodala** [helhum/typo3-composer-setup#1]
Normally one can access the TYPO3 Install Tool from outside of the TYPO3 backend e.g. via `https://example.org/typo3/install` or `https://example.org/typo3/install/`. This is achieved with a directory and file, thus `.../install/index.php`.

This package however uses `.../install.php` instead of `.../install/index.php`. IMHO this should be changed to reflect the traditional URL structure.

**Comment by helhum** [comment]
Thanks @mbrodala. You are right, that I don't expose `typo3/install/index.php` as entry point, when you use this package. Neither does TYPO3 since version 9.0

Even TYPO3 v8 has `typo3/install.php` as main entry point and the other two (`typo3/install/index.php` and `typo3/sysext/install/Start/Install.php`) redirect to `typo3/install.php`.

Although it could be a nice fallback for users used to use the old entry points, I have no plans to support them within this package.

If you need those redirects and still want to use this package, I suggest you add the redirects to your webserver configuration.

**Comment by mbrodala** [comment]
Fair enough. :-)
